"use strict";
/** @type {import('sequelize-cli').Migration} */
module.exports = {
    up: async (queryInterface, Sequelize) => {
        await queryInterface.bulkInsert("Properties", [
            {
                propertyId: 1,
                propertyName: "Property 1",
                propertyType: "Apartment",
                propertySize: "2BHK",
                propertyRent: 15000,
                currencyId:1,
                propertyStatus: 1,
                propertyPic: "property1.jpg",
                propertyDescription: "Property 1 Description",
                propertyFacility: "Property 1 Facility",
                userId: 1,
                addressId: 1,
                note: "Property 1 Note",
            },
            {
                propertyId: 2,
                propertyName: "Property 2",
                propertyType: "Villa",
                propertySize: "3BHK",
                propertyRent: 25000,
                currencyId:2,
                propertyStatus: 1,
                propertyPic: "property2.jpg",
                propertyDescription: "Property 2 Description",
                propertyFacility: "Property 2 Facility",
                userId: 2,
                addressId: 2,
                note: "Property 2 Note",
            },
            {
                propertyId: 3,
                propertyName: "Property 3",
                propertyType: "Independent House",
                propertySize: "4BHK",
                propertyRent: 35000,
                currencyId:3,
                propertyStatus: 1,
                propertyPic: "property3.jpg",
                propertyDescription: "Property 3 Description",
                propertyFacility: "Property 3 Facility",
                userId: 3,
                addressId: 3,
                note: "Property 3 Note",
            },
            {
                propertyId: 4,
                propertyName: "Property 4",
                propertyType: "Penthouse",
                propertySize: "5BHK",
                propertyRent: 45000,
                currencyId:3,
                propertyStatus: 1,
                propertyPic: "property4.jpg",
                propertyDescription: "Property 4 Description",
                propertyFacility: "Property 4 Facility",
                userId: 1,
                addressId: 4,
                note: "Property 4 Note",
            },
            {
                propertyId: 5,
                propertyName: "Property 5",
                propertyType: "Duplex",
                propertySize: "6BHK",
                propertyRent: 55000,
                currencyId:2,
                propertyStatus: 1,
                propertyPic: "property5.jpg",
                propertyDescription: "Property 5 Description",
                propertyFacility: "Property 5 Facility",
                userId: 1,
                addressId: 4,
                note: "Property 5 Note",
            },
            {
                propertyId: 6,
                propertyName: "Property 6",
                propertyType: "Studio",
                propertySize: "1BHK",
                propertyRent: 65000,
                currencyId:1,
                propertyStatus: 1,
                propertyPic: "property6.jpg",
                propertyDescription: "Property 6 Description",
                propertyFacility: "Property 6 Facility",
                userId: 1,
                addressId: 4,
                note: "Property 6 Note",
            },
        ]);
    }

    }