"use strict";
/** @type {import('sequelize-cli').Migration} */
module.exports = {
    up: async (queryInterface, Sequelize) => {
        await queryInterface.bulkInsert("Rooms", [
            {
                roomId: 1,
                roomNo: 101,
                propertyId: 1,
                userId: 1,
                roomType: "1BHK",
                roomSize: "500 sqft",
                roomRent: 10000,
                currencyId: 1,
                roomStatus: 1,
                roomPic: "room1.jpg",
                roomDescription: "Room 1 Description",
                roomFacility: "Room 1 Facility",
                addressId: 1,
                roomCapacity: 1,
                currentTenantCount: 1,
                note: "Room 1 Note",
                createdBy: 1,
                lastModifiedBy: 1,
            },
            {
                roomId: 2,
                roomNo: 201,
                propertyId: 2,
                userId: 2,
                roomType: "2BHK",
                roomSize: "800 sqft",
                roomRent: 20000,
                currencyId: 2,
                roomStatus: 1,
                roomPic: "room2.jpg",
                roomDescription: "Room 2 Description",
                roomFacility: "Room 2 Facility",
                addressId: 2,
                roomCapacity: 2,
                currentTenantCount: 2,
                note: "Room 2 Note",
                createdBy: 2,
                lastModifiedBy: 2,
            },
            {
                roomId: 3,
                roomNo: 301,
                propertyId: 3,
                userId: 3,
                roomType: "3BHK",
                roomSize: "1200 sqft",
                roomRent: 30000,
                currencyId: 3,
                roomStatus: 1,
                roomPic: "room3.jpg",
                roomDescription: "Room 3 Description",
                roomFacility: "Room 3 Facility",
                addressId: 3,
                roomCapacity: 3,
                currentTenantCount: 3,
                note: "Room 3 Note",
                createdBy: 3,
                lastModifiedBy: 3,
            },
            {
                roomId: 4,
                roomNo: 401,
                propertyId: 4,
                userId: 4,
                roomType: "4BHK",
                roomSize: "1600 sqft",
                roomRent: 400000,
                currencyId: 1,
                roomStatus: 1,
                roomPic: "room4.jpg",
                roomDescription: "Room 4 Description",
                roomFacility: "Room 4 Facility",
                addressId: 4,
                roomCapacity: 4,
                currentTenantCount: 4,
                note: "Room 4 Note",
                createdBy: 4,
                lastModifiedBy: 4,
            },
        ]);
    }
};